# Generated by Django 4.2.6 on 2023-10-18 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('detalle', models.CharField(max_length=100)),
                ('detalle_corto', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('S', 'Suspencion de actividades'), ('C', 'Suspencion de clase'), ('I', 'Informacion')], max_length=100)),
                ('visible', models.BooleanField(verbose_name=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultima_publicacion', models.DateTimeField(blank=True, null=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.entidad')),
            ],
        ),
    ]
