# Generated by Django 4.2.6 on 2023-10-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_comunicado_modificado_por_comunicado_publicado_por'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entidad',
            options={'verbose_name': 'Entidad', 'verbose_name_plural': 'Entidades'},
        ),
        migrations.AlterField(
            model_name='entidad',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='CERTAMEN\x07lbum'),
        ),
    ]
