# Generated by Django 4.2.6 on 2023-10-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_entidad_options_alter_entidad_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='fecha_ultima_publicacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
