# Generated by Django 4.2.6 on 2023-10-22 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_comunicado_fecha_publicacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comunicado',
            old_name='modificado_por',
            new_name='_modificado_por',
        ),
        migrations.RenameField(
            model_name='comunicado',
            old_name='publicado_por',
            new_name='_publicado_por',
        ),
    ]
