# Generated by Django 4.2.6 on 2023-10-22 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_modificado_por_comunicado__modificado_por_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunicado',
            name='_modificado_por',
        ),
        migrations.RemoveField(
            model_name='comunicado',
            name='_publicado_por',
        ),
    ]
