# Generated by Django 4.2.6 on 2023-10-22 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_comunicado__modificado_por_comunicado__publicado_por'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comunicado',
            old_name='_modificado_por',
            new_name='modificado_por',
        ),
        migrations.RenameField(
            model_name='comunicado',
            old_name='_publicado_por',
            new_name='publicado_por',
        ),
    ]
