# Generated by Django 4.2.6 on 2023-10-22 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0008_rename__modificado_por_comunicado_modificado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
