# Generated by Django 4.2.6 on 2023-10-22 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_entidad_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entidad',
            old_name='admin',
            new_name='administrador',
        ),
    ]
