# Generated by Django 4.2.6 on 2023-10-23 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0011_alter_comunicado_entidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='administrador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='fotos'),
        ),
    ]
