# Generated by Django 4.2.6 on 2023-10-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_entidad_administrador_alter_entidad_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='visible',
            field=models.BooleanField(),
        ),
    ]
